// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MenuZen.Domain.Tests.Features.CategorieIngredients
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CréerCatégorieIngrédients")]
    public partial class CreerCategorieIngredientsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("fr"), "Features/CatégorieIngrédients", "CréerCatégorieIngrédients", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "CréerCatégorieIngrédients.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Créer une catégorie d\'ingrédients avec succès")]
        [NUnit.Framework.TestCaseAttribute("Viandes", "IconeViande", "Rouge", null)]
        public async System.Threading.Tasks.Task CreerUneCategorieDingredientsAvecSucces(string nomCategorieIngredients, string iconeCategorieIngredients, string couleurCategorieIngredients, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("NomCatégorieIngrédients", nomCategorieIngredients);
            argumentsOfScenario.Add("IcôneCatégorieIngrédients", iconeCategorieIngredients);
            argumentsOfScenario.Add("CouleurCatégorieIngrédients", couleurCategorieIngredients);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Créer une catégorie d\'ingrédients avec succès", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await testRunner.GivenAsync(string.Format("un nom de catégorie d ingrédients \'{0}\'", nomCategorieIngredients), ((string)(null)), ((global::Reqnroll.Table)(null)), "Etant donné ");
#line hidden
#line 6
 await testRunner.AndAsync(string.Format("une icône de catégorie d ingrédients \'{0}\'", iconeCategorieIngredients), ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
#line 7
 await testRunner.AndAsync(string.Format("une couleur de catégorie d ingrédients \'{0}\'", couleurCategorieIngredients), ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
#line 8
 await testRunner.WhenAsync("je crée une catégorie d\'ingrédients", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 9
 await testRunner.ThenAsync("la catégorie est crée avec succès", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
#line 10
 await testRunner.AndAsync(string.Format("le nom de la catégorie d ingrédients est \'{0}\'", nomCategorieIngredients), ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
#line 11
 await testRunner.AndAsync(string.Format("l icône de catégorie d ingrédients est \'{0}\'", iconeCategorieIngredients), ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
#line 12
 await testRunner.AndAsync(string.Format("la couleur de catégorie d ingrédients est \'{0}\'", couleurCategorieIngredients), ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
